Update beadm

diff --git a/beadm b/beadm
--- a/beadm
+++ b/beadm
@@ -1,9 +1,11 @@
 #!/bin/sh -e
 
-# Copyright (c) 2012-2019 Slawomir Wojciech Wojtczak (vermaden)
+# Copyright (c) 2012-2020 Slawomir Wojciech Wojtczak (vermaden)
 # Copyright (c) 2012-2013 Bryan Drewery (bdrewery)
 # Copyright (c) 2012-2013 Mike Clarke (rawthey)
 # Copyright (c) 2013      Dancho Penev (dpslavov)
+# Copyright (c) 2020      J.M. Rivera (JRGTH)
+
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -37,7 +39,7 @@ fi
 
 if [ "${1}" = "--version" -o "${1}" = "-version" -o "${1}" = "version" ]
 then
-  echo "beadm 1.3.0 2019/05/02"
+  echo "beadm 1.3.1 2020/07/22"
   exit 0
 fi
 
@@ -48,8 +50,8 @@ __usage() {
   echo "  ${NAME} create [-e nonActiveBe | -e beName@snapshot] <beName>"
   echo "  ${NAME} create <beName@snapshot>"
   echo "  ${NAME} destroy [-F] <beName | beName@snapshot>"
-  echo "  ${NAME} export [-v] sourceBe"
-  echo "  ${NAME} import [-v] targetBe"
+  echo "  ${NAME} export [-v] <beName>"
+  echo "  ${NAME} import [-v] <beName>"
   echo "  ${NAME} list [-a] [-s] [-D] [-H]"
   echo "  ${NAME} rename <origBeName> <newBeName>"
   echo "  ${NAME} mount <beName> [mountpoint]"
@@ -62,12 +64,12 @@ __usage() {
 BOOTPATH=
 if [ -L '/boot' ] && [ -d '/boot' ]
 then
-    BOOTPOOL=$( readlink '/boot' | awk -F '/' '{print $1}' )
-    BOOTPROP=$( zpool list -H -o bootfs ${BOOTPOOL} )
-    if [ "${BOOTPROP}" = "-" ]
-    then
-        BOOTPATH=/${BOOTPOOL}
-    fi
+  BOOTPOOL=$( readlink '/boot' | awk -F '/' '{print $1}' )
+  BOOTPROP=$( zpool list -H -o bootfs ${BOOTPOOL} )
+  if [ "${BOOTPROP}" = "-" ]
+  then
+    BOOTPATH=/${BOOTPOOL}
+  fi
 fi
 
 # check if system has a grub.cfg file and update it
@@ -272,8 +274,8 @@ BOOTFS=$( zpool list -H -o bootfs ${POOL} )
 
 if [ -z "${BOOTFS}" -o "${BOOTFS}" = "-" ]
 then
- echo "ERROR: ZFS boot pool '${POOL}' has unset 'bootfs' property"
- exit 1
+  echo "ERROR: ZFS boot pool '${POOL}' has unset 'bootfs' property"
+  exit 1
 fi
 
 if [ -f /usr/local/etc/beadm.conf ]
@@ -585,10 +587,10 @@ EOF
         fi
         if [ -f /boot/zfs/zpool.cache ]
         then
-            if [ -z "${BOOTPATH}" ]
-            then
-                cp /boot/zfs/zpool.cache ${TMPMNT}/boot/zfs/zpool.cache
-            fi
+          if [ -z "${BOOTPATH}" ]
+          then
+            cp /boot/zfs/zpool.cache ${TMPMNT}/boot/zfs/zpool.cache
+          fi
         else
           rm -f ${TMPMNT}/boot/zfs/zpool.cache
         fi
@@ -597,14 +599,14 @@ EOF
         then
           LOADER_CONFIGS="${LOADER_CONFIGS} ${TMPMNT}/boot/loader.conf.local"
         else
-            if [ -n "${BOOTPATH}" ]
+          if [ -n "${BOOTPATH}" ]
+          then
+            LOADER_CONFIGS=${BOOTPATH}/boot/loader.conf
+            if [ -f ${BOOTPATH}/boot/loader.conf.local ]
             then
-                LOADER_CONFIGS=${BOOTPATH}/boot/loader.conf
-                if [ -f ${BOOTPATH}/boot/loader.conf.local ]
-                then
-                    LOADER_CONFIGS="${LOADER_CONFIGS} ${BOOTPATH}/boot/loader.conf.local"
-                fi
+              LOADER_CONFIGS="${LOADER_CONFIGS} ${BOOTPATH}/boot/loader.conf.local"
             fi
+          fi
         fi
         sed -i '' -E s/"^vfs.root.mountfrom=.*$"/"vfs.root.mountfrom=\"zfs:${POOL}\/${BEDS}\/${2##*/}\""/g ${LOADER_CONFIGS}
         if [ ${MOUNT} -eq 0 ]
@@ -740,7 +742,7 @@ EOF
           fi
           # destroy boot environment
           zfs destroy -r ${POOL}/${BEDS}/${DESTROY}
-           # check if boot environment is a clone
+          # check if boot environment is a clone
           if __be_clone ${POOL}/${BEDS}/${DESTROY}
           then
             # promote datasets dependent on origins used by destroyed boot environment
@@ -799,15 +801,15 @@ EOF
       __usage
     fi
     __be_exist ${POOL}/${BEDS}/${ITEM}
-    # always take a recent snapshot before export
+    # always take recent snapshot before export
     FMT=$( date "+%Y-%m-%d-%H:%M:%S" )
     if ! zfs snapshot -r ${POOL}/${BEDS}/${ITEM}@${FMT} 1> /dev/null 2> /dev/null
     then
-      echo "ERROR: Cannot create '${ITEM}' recursive snapshot"
+      echo "ERROR: Cannot create '${ITEM}' snapshot"
       exit 1
     fi
-    # send a piped/redirected zfs data stream
-    zfs send ${OPTS} ${POOL}/${BEDS}/${ITEM}@${FMT};
+    # send piped/redirected zfs data stream
+    zfs send ${OPTS} ${POOL}/${BEDS}/${ITEM}@${FMT}
     ;;
 
   (import) # -----------------------------------------------------------------
@@ -827,8 +829,8 @@ EOF
       echo "ERROR: Boot environment '${ITEM}' already exists"
       exit 1
     fi
-    # receive a piped/redirected zfs data stream
-    zfs recv ${OPTS} ${POOL}/${BEDS}/${ITEM};
+    # receive piped/redirected zfs data stream
+    zfs recv ${OPTS} ${POOL}/${BEDS}/${ITEM}
     ;;
 
   (rename) # ------------------------------------------------------------------
@@ -864,7 +866,7 @@ EOF
   (mount) # ------------------------------------------------------------
     if [ ${#} -eq 2 ]
     then
-      TARGET=$( mktemp -d -t BE-${2} )
+      TARGET=$( env TMPDIR=/var/tmp mktemp -d -t BE-${2} )
     elif [ ${#} -eq 3 ]
     then
       TARGET=${3}
