Add new -r option to beadm list, which will bypass nickname and display the raw dataset name

diff --git a/beadm b/beadm
--- a/beadm
+++ b/beadm
@@ -49,7 +49,7 @@ __usage() {
   echo "  ${NAME} create [-e nonActiveBe | -e beName@snapshot] <beName> [nickname]"
   echo "  ${NAME} create <beName@snapshot> [nickname]"
   echo "  ${NAME} destroy [-F] <beName | beName@snapshot | nickname>"
-  echo "  ${NAME} list [-a] [-s] [-D] [-H]"
+  echo "  ${NAME} list [-a] [-s] [-D] [-H] [-r]"
   echo "  ${NAME} rename <origBeName> <newBeName>"
   echo "  ${NAME} mount <beName> [mountpoint]"
   echo "  ${NAME} { umount | unmount } [-f] <beName>"
@@ -80,7 +80,7 @@ __be_exist() { # 1=DATASET
 
 # check if boot environment nickname exists
 __be_nickname_exist() { # 1=NICKNAME
-  zfs get -d 2 beadm:nickname ${POOL}/${BEDS} | grep -v "^NAME" | awk -Fbeadm:nickname '{print $2}' | awk -Finherited '{print $1}' | awk -Flocal '{print $1}' | sed -e 's/^ *//' -e 's/ *$//' | grep -q -w "$1"
+  zfs get -d 2 -H -o value beadm:nickname ${POOL}/${BEDS} | grep -q -w "$1"
   return $?
 }
 
@@ -130,15 +130,6 @@ __be_new() { # 1=SOURCE 2=TARGET 3=NICKNAME
             exit 1
           fi
         done
-    # Set nickname
-    if [ -n "${NICKNAME}" ]
-    then
-      zfs set beadm:nickname="${NICKNAME}" ${1}@${SNAPSHOT}
-      if [ $? -ne 0 ]
-      then
-        echo "WARNING: Unable to set nickname!"
-      fi
-    fi
   else
     # create boot environment from other boot environment
     if zfs list -H -o name ${1}@${2##*/} 1> /dev/null 2> /dev/null
@@ -152,15 +143,6 @@ __be_new() { # 1=SOURCE 2=TARGET 3=NICKNAME
     then
       echo "ERROR: Cannot create snapshot '${1}@${FMT}'"
       exit 1
-    fi
-    # Set nickname
-    if [ -n "${NICKNAME}" ]
-    then
-      zfs set beadm:nickname="${NICKNAME}" ${1}@${FMT}
-      if [ $? -ne 0 ]
-      then
-        echo "WARNING: Unable to set nickname!"
-      fi
     fi
   fi
   # clone properties of source boot environment
@@ -190,6 +172,15 @@ EOF
           eval "zfs clone -o canmount=off ${OPTS} ${FS}@${1##*@} ${DATASET}"
         else
           eval "zfs clone -o canmount=off ${OPTS} ${FS}@${FMT} ${DATASET}"
+        fi
+        # Set nickname
+        if [ -n "${NICKNAME}" ]
+        then
+          zfs set beadm:nickname="${NICKNAME}" ${DATASET}
+          if [ $? -ne 0 ]
+          then
+            echo "WARNING: Unable to set nickname!"
+          fi
         fi
       done
 
@@ -240,14 +231,17 @@ case ${1} in
   (list) # --------------------------------------------------------------------
     OPTION_a=0
     OPTION_D=0
+    OPTION_H=0
+    OPTION_r=0
     OPTION_s=0
     shift
-    while getopts "aDHs" OPT
+    while getopts "aDHrs" OPT
     do
       case ${OPT} in
         (a) OPTION_a=1 ;;
         (D) OPTION_D=1 ;;
         (H) OPTION_H=1 ;;
+        (r) OPTION_r=1 ;;
         (s) OPTION_s=1
             OPTION_a=1 ;;
         (*) __usage    ;;
@@ -260,6 +254,7 @@ case ${1} in
         -v OPTION_a="${OPTION_a}" \
         -v OPTION_D="${OPTION_D}" \
         -v OPTION_H="${OPTION_H}" \
+        -v OPTION_r="${OPTION_r}" \
         -v OPTION_s="${OPTION_s}" \
      'function __normalize(VALUE) {
         if(VALUE == "-" || VALUE == 0)
@@ -363,6 +358,13 @@ case ${1} in
           SNAPSHOT_FILTER = "(/[^@]*)?$"
         for(I = 1; I <= length(BENAMES); I++) {
           BENAME = BENAMES[I]
+          CMD_ZFS_NICK = "zfs get -d 2 -H -o value beadm:nickname " POOL "/" BEDS "/" BENAME
+          while(CMD_ZFS_NICK | getline) {
+	    if ($1 != "-")
+              if(OPTION_r != 1)
+	        BENAME=$1
+	  }
+
           if(OPTION_a == 1) {
             printf "\n"
             print BENAME
