Update beadm "create" to do proper parsing of flags, and do nickname replacment. Update man page as well.

diff --git a/beadm b/beadm
--- a/beadm
+++ b/beadm
@@ -46,9 +46,7 @@ __usage() {
   local NAME=${0##*/}
   echo "usage:"
   echo "  ${NAME} activate <beName>"
-  echo "  ${NAME} create [-e nonActiveBe | -e beName@snapshot] <beName> [nickname]"
-  echo "  ${NAME} create -r <beName> <replaceNickName>"
-  echo "  ${NAME} create <beName@snapshot> [nickname]"
+  echo "  ${NAME} create [-r] [-e nonActiveBe | -e beName@snapshot] <beName>/<beName@snapshot> [nickname]"
   echo "  ${NAME} destroy [-F] <beName | beName@snapshot | nickname>"
   echo "  ${NAME} list [-a] [-s] [-D] [-H] [-r]"
   echo "  ${NAME} rename <origBeName> <newBeName>"
@@ -93,7 +91,7 @@ __be_get_nickname() {
   then
      return 1
   fi
-  BENICKNAME=`zfs get -d 1 -H -o value beadm:nickname ${1} | awk '{print $1}' | head -n 1 | sed 's|-||g'`
+  BENICKNAME=`zfs get -d 1 -H -o value beadm:nickname ${1} | head -n 1 | sed 's|-||g'`
   if [ -z "$BENICKNAME" ] ; then
     return 1
   else
@@ -490,91 +488,112 @@ case ${1} in
     ;;
 
   (create) # ------------------------------------------------------------------
+    OPTION_r=0
+    OPTION_e=0
+    CLONEBE=""
+    NEWBE=""
+    BENICK=""
     REPLACEBENICK=0
-    case ${#} in
-      (4|5)
-        if ! [ ${2} = "-e" -o ${2} = "-r" ]
-        then
-          __usage
-        fi
-        if [ ${2} = "-e" ]
-	then
-          # check if argument for -e option is full path dataset
-          # argument for -e option must be 'beName' or 'beName@snapshot'
-          if echo ${3} | grep -q "/" 2> /dev/null
-          then
-            __usage
-          fi
-          __be_exist ${POOL}/${BEDS}/${3}
-          if zfs list -H -o name ${POOL}/${BEDS}/${4} 1> /dev/null 2> /dev/null
-          then
-            echo "ERROR: Boot environment '${4}' already exists"
-            exit 1
-          fi
-	  if [ -n "${5}" ]
-	  then
-            if zfs list -H -o name "${POOL}/${BEDS}/${5}" 1> /dev/null 2> /dev/null
+    while [ $# -gt 0 ]; do
+      case "$1" in
+    create) ;;
+        -e) shift
+	    OPTION_e=1
+	    CLONEBE="$1"
+	    if [ -z "$CLONEBE" ]
+	    then
+	      __usage
+	    fi
+            # check if argument for -e option is full path dataset
+            # argument for -e option must be 'beName' or 'beName@snapshot'
+            if echo ${CLONEBE} | grep -q "/" 2> /dev/null
             then
-              echo "ERROR: Boot environment '${5}' already exists"
-              exit 1
+               __usage
             fi
-	    if __be_nickname_exist "${5}"
+            __be_exist ${POOL}/${BEDS}/${CLONEBE}
+            ;;
+        -r) OPTION_r=1
+            ;;
+         *) if [ -z "$NEWBE" ]
 	    then
-              echo "ERROR: Boot environment nickname '${5}' already exists"
-              exit 1
+               NEWBE="$1"
+	       shift
+               continue
 	    fi
-	    BENICK="${5}"
-	  fi
-          __be_new ${POOL}/${BEDS}/${3} ${POOL}/${BEDS}/${4}
-	fi
-        if [ ${2} = "-r" ]
-	then
-          if zfs list -H -o name ${POOL}/${BEDS}/${3} 1> /dev/null 2> /dev/null
-          then
-            echo "ERROR: Boot environment '${3}' already exists"
-            exit 1
-          fi
-	  if __be_nickname_exist "${4}"
-	  then
-            echo "ERROR: Boot environment nickname '${4}' already exists"
-            exit 1
-	  fi
-	  if ! __be_get_nickname ${ROOTFS}
-	  then
-            echo "ERROR: Boot environment '${ROOTFS}' does not have a nickname"
-            exit 1
-	  fi
-	  OLDBENICK="${BENICKNAME}"
-	  BENICK="${4}"
-	  REPLACEBENICK=1
-          __be_new ${ROOTFS} ${POOL}/${BEDS}/${3}
-	fi
-        ;;
-      (2|3)
-        if __be_snapshot ${2}
+	    if [ -z "$BENICK" ]
+	    then
+               BENICK="${1}"
+               if zfs list -H -o name "${POOL}/${BEDS}/${BENICK}" 1> /dev/null 2> /dev/null
+               then
+                 echo "ERROR: Boot environment '${BENICK}' already exists"
+                 exit 1
+               fi
+               if __be_nickname_exist "${BENICK}"
+               then
+		 if [ ${OPTION_r} -ne 1 ]
+                 then
+                   echo "ERROR: Boot environment nickname '${BENICK}' already exists"
+                   exit 1
+                 fi
+               fi
+	       shift
+               continue
+	    fi
+	    __usage
+            ;;
+      esac
+      shift
+    done
+
+    if [ -z "$NEWBE" ] ; then
+       __usage
+    fi
+
+    FROMBE=""
+    if [ "${OPTION_e}" -eq 1 ]
+    then
+      if zfs list -H -o name ${POOL}/${BEDS}/${NEWBE} 1> /dev/null 2> /dev/null
+      then
+        echo "ERROR: Boot environment '${NEWBE}' already exists"
+        exit 1
+      fi
+      FROMBE="${POOL}/${BEDS}/${CLONEBE}"
+    else
+      # Creating from the ROOTFS
+      if __be_snapshot ${NEWBE}
+      then
+        if ! zfs snapshot -r ${POOL}/${BEDS}/${NEWBE} 1> /dev/null 2> /dev/null
         then
-          if ! zfs snapshot -r ${POOL}/${BEDS}/${2} 1> /dev/null 2> /dev/null
-          then
-            echo "ERROR: Cannot create '${2}' recursive snapshot"
-            exit 1
-          fi
-        else
-	  if [ -n "${3}" ]
-	  then
-	    if __be_nickname_exist "${3}"
-	    then
-              echo "ERROR: Boot environment nickname '${3}' already exists"
-              exit 1
-	    fi
-	    BENICK="${3}"
-	  fi
-          __be_new ${ROOTFS} ${POOL}/${BEDS}/${2}
+          echo "ERROR: Cannot create '${NEWBE}' recursive snapshot"
+          exit 1
         fi
-        ;;
-      (*)
-        __usage
-        ;;
-    esac
+      fi
+      FROMBE="${ROOTFS}"
+    fi
+
+    if [ "${OPTION_r}" -eq 1 ]
+    then
+      if zfs list -H -o name ${POOL}/${BEDS}/${BENICK} 1> /dev/null 2> /dev/null
+      then
+        echo "ERROR: Boot environment '${BENICK}' already exists"
+        exit 1
+      fi
+      if __be_nickname_exist "${BENICK}"
+      then
+        echo "ERROR: Boot environment nickname '${BENICK}' already exists"
+        exit 1
+      fi
+      if ! __be_get_nickname ${FROMBE} 1> /dev/null 2>/dev/null
+      then
+        echo "ERROR: Boot environment '${FROMBE}' does not have a nickname"
+        exit 1
+      fi
+      OLDBENICK="${BENICK}"
+      BENICK="${BENICKNAME}"
+      REPLACEBENICK=1
+    fi
+
+    __be_new ${FROMBE} ${POOL}/${BEDS}/${NEWBE}
     echo "Created successfully"
     ;;
 
